Unit and E2E test cases for dtc servers and dtc pools
infobloxopen/infoblox-go-client pull request #262
Opened 2024-12-03 09:00 UTC by Chaithra001

Unit test cases for dtc servers 
Unit test cases for dtc pools 
E2E test cases for dtc pools

2024-12-06 06:46 UTC, Aish-sp requested changes

2024-12-06 06:46 UTC, Aish-sp commented on object_manager.go
1. Parameters names to begin with small letter in the function declaration in CreateDtcPool, CreateDtcServer, UpdateDtcPool, UpdateDtcServer
2. Typo in GetDtcServer(**ueryParams**) --> queryParams

2024-12-06 06:46 UTC, Aish-sp commented on object_manager_dtc_pool.go
Variables used only inside functions need to have names starting with small letter  --> TopologyFields and rest of the variables in this file.

2024-12-09 06:21 UTC, Chaithra001 commented
Changes are in a different PR 
https://github.com/infobloxopen/infoblox-go-client/pull/263

Closing the PR here

2024-12-09 06:21 UTC, closed without merging